### ISSUE TITLE
Question about drawing package

### ISSUE THREAD

**Issue by bpinaya** [mit-racecar/hardware#3]
Hi there, I was just wondering what drawing package you used to make the designs. It looks like SolidWorks but I can't be sure, mind telling which one you used? 
Kind regards

**Comment by sourabhrajwade** [comment]
Hi!
I am looking at the design. I just want to know about the suspension design.

**Comment by mboulet** [comment]
@bpinaya Yes, it is Solidworks for the 3D models. Visio was used to create some of the 2D drawings.

@sourabhrajwade We sometimes add stiffer springs to the suspension due to the weight of the processor and sensors. Otherwise it is out-of-the-box Traxxas suspension.
